hr/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('', loginpage, name='login'),
    path('index/', index, name='index'),
    path('logout/',logoutpage ,name='logout'),
    path('my_profile/',my_profile,name='my_profile'),
    path('view_all_employee/',view_all_employee,name='view_all_employee'),
    path('deactivate_employee_/<int:id>/', deactivate_employee, name='deactivate_employee'),
    path('update_employee/<int:id>',update_employee,name="update_employee"),
    path('add_department/',add_department,name='add_department'),
    path('view_department/',view_department,name='view_department'),
    path('fill_attendance/',fill_attendance,name='fill_attendance'),
    path('attendence_request/',attendence_request,name='attendence_request'),
    path('view_attendence_requests/',view_attendence_requests,name='view_attendence_requests'),
    path('view_attendences/', view_attendences, name='view_attendences'),
    path('download_attendance_csv/', download_attendance_csv, name='download_attendance_csv_default'),
    path('add_employee/', add_employee, name='add_employee'),
    path('download_attendance_csv/<str:start_date>/<str:end_date>/', download_attendance_csv, name='download_attendance_csv'),
    path('change_password/', change_password, name='change_password'),
    path('accept-reject-attendance/<int:attendance_id>/<str:action>/', accept_reject_attendance, name='accept_reject_attendance'),
    path('leave_application/',leave_application,name='leave_application'),
    path('view_all_leaves/',view_all_leaves,name='view_all_leaves'),
    path('approve_leave/<int:id>/<str:action>/', approve_leave, name='approve_leave'),
    path('track_leave/',track_leave,name='track_leave'),
    path('cancel_leave/<int:id>/', cancel_leave, name='cancel_leave'),
    path('landing_page', landing_page, name='landing_page'),
    path('show_attendence_graph', show_attendence_graph, name='show_attendence_graph'),
    path('contact_us', contact_us, name='contact_us'),
    path('about_us', about_us, name='about_us'),


]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hr.urls'))
]

hr/models.py
from django.db import models
from django.contrib.auth.models import User


class Department(models.Model):
    id = models.BigAutoField(unique=True, primary_key=True)
    department_name = models.CharField(max_length=50)
    added_by = models.ForeignKey(
        User, on_delete=models.CASCADE, default=None, null=True, blank=True)

    def __str__(self):
        return self.department_name


class Designation(models.Model):
    id = models.BigAutoField(unique=True, primary_key=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class City(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class State(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


EMP_TYPE_CHOICES = [
    ('Full-time', 'full-time'), ('Part-time', 'part-time'), ('Casual', 'casual'),
    ('Trainee', 'trainee'), ('Probation', 'probation'), ('Comission', 'comission'),
]


class Employee(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.BigAutoField(primary_key=True)
    emp_code = models.CharField(unique=True, max_length=20)  # emp id for login
    profile = models.ImageField(upload_to="images", blank=True, null=True)
    email = models.EmailField()
    mobile_number = models.CharField(max_length=13, null=True, blank=True)
    date_of_birth = models.DateField()
    employee_address = models.TextField(max_length=1000)
    city_id = models.ForeignKey(
        City, null=True, blank=True, on_delete=models.CASCADE)
    state_id = models.ForeignKey(
        State, null=True, blank=True, on_delete=models.CASCADE)
    aadhar_number = models.CharField(
        max_length=12, null=True, blank=True, unique=True)
    pan_number = models.CharField(
        max_length=10, null=True, blank=True, unique=True)
    dep_id = models.ForeignKey(
        Department, null=True, blank=True, on_delete=models.CASCADE)
    designation_id = models.ForeignKey(
        Designation, null=True, blank=True, on_delete=models.CASCADE)
    date_of_joining = models.DateField()
    is_hr = models.BooleanField(default=False)
    is_employee = models.BooleanField(default=False)

    def __str__(self):
        return self.emp_code


class Leavetype(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Leaves(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    leavetype_id = models.ForeignKey(
        Leavetype, on_delete=models.CASCADE, default=None)
    emp_id = models.ForeignKey(
        Employee, on_delete=models.CASCADE, default=None)
    fro = models.DateField(null=True)
    to = models.DateField(null=True)
    num_of_days = models.FloatField(default=0)
    status = models.CharField(max_length=20, choices=[('pending', 'Pending'), (
        'cancel', 'Cancel'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')
    description = models.TextField(null=True)

    def __str__(self):
        return self.emp_id.user.username


class Attendance(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    emp_id = models.ForeignKey(
        Employee, on_delete=models.CASCADE, default=None)
    att_date = models.DateField()
    in_time = models.TimeField()
    out_time = models.TimeField(null=True, blank=True)

    def __str__(self):
        return self.emp_id.user.username


class RequestedAttendance(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    emp_id = models.ForeignKey(
        Employee, on_delete=models.CASCADE, default=None)
    att_date = models.DateField()
    in_time = models.TimeField()
    out_time = models.TimeField(null=True, blank=True)
    request_type = models.CharField(max_length=10, choices=[(
        'new', 'New Request'), ('change', 'Change Request')], default='new')
    status = models.CharField(max_length=20, choices=[('pending', 'Pending'), (
        'approved', 'Approved'), ('rejected', 'Rejected')], default='pending')
    note = models.TextField(max_length=300, null=True, blank=True)

    def __str__(self):
        return self.emp_id.user.username

hr/views.py
import csv
import datetime
import time
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import *
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
import plotly.graph_objs as go

# Create your views here.

@csrf_protect
def loginpage(request):

    if request.session.get('username'):

        user = User.objects.filter(username=request.session.get('username'))
        emp_id = Employee.objects.filter(user=user.first()).first()
        context = {
            'username': request.session.get('username'),
            'emp': emp_id,
            'is_hr': emp_id.is_hr
        }
        return render(request, 'index.html', context)
    else:
        if request.method == 'POST':
            username = request.POST.get('uname')
            password = request.POST.get('pass')

            user = authenticate(username=username, password=password)

            print(user)
            if user is not None:
                
                emp_id = Employee.objects.filter(user=user).first()
                login(request, user)
                request.session['username'] = username
                return render(request, 'index.html', {
                    'is_hr': emp_id.is_hr,
                    'emp': emp_id,
                })
            else:
                if User.objects.filter(username=username).exists():
                    messages.warning(request, 'Your password is incorrect')
                    # return render(request, 'login.html', {'error': 'not'})

                else:
                    # return render(request, 'login.html', {'error': 'yes'})
                    messages.warning(request, 'your username is Incorrect')
                # return HttpResponse("plese Enter correct password")
                
        return render(request, 'login.html')

def logoutpage(request):
    # Remove the 'username' from the session
    if 'username' in request.session:
        del request.session['username']
    
    logout(request)
    
    return redirect('login')

@csrf_protect
def add_employee(request):
    if request.method=='POST':
        # data = request.POST
        profile = request.FILES.get('profile')
        emp_code = request.POST.get('user')
        department=request.POST.get('Department')
        first_name=request.POST.get('first_name')
        last_name=request.POST.get('last_name')
        mobile_number=request.POST.get('mobile_number')
        email=request.POST.get('email')
        dob=request.POST.get('dob')
        employee_address=request.POST.get('employee_address')
        state=request.POST.get('state')
        city=request.POST.get('city')
        aadhar_number=request.POST.get('aadhar_number')
        pan_number=request.POST.get('pan_number')
        emp_designation=request.POST.get('designation')
        date_of_joining=request.POST.get('date_of_joining')
        password = request.POST.get('password')
        cpassword = request.POST.get('cpassword')
        
        try:
            if password != cpassword:
                messages.warning(request, 'your password and confirm password not same')
                
            if len(aadhar_number) > 12 or len(aadhar_number) < 12:
                messages.warning(request, 'Aadhar Number length should be 12 digit only')
            
            aadhar_match_user = Employee.objects.filter(aadhar_number=aadhar_number)
            if aadhar_match_user.first():
                messages.warning(request, 'Employee with this aadhar number already exist!!')
                
                
                
            if state:
                state_id = State.objects.get(name=state)
                    
            if city:
                city_id = City.objects.get(name=city)

            if department:
                dep_id = Department.objects.get(department_name=department)

            if emp_designation:
                designation_id = Designation.objects.get(name=emp_designation)

            user_id = User.objects.create(username=emp_code,first_name=first_name, last_name=last_name, email=email)
            user_id.set_password(password)
            user_id.save()
            
            emp_id = Employee.objects.create(user=user_id,emp_code=emp_code,profile=profile, email=email, mobile_number=mobile_number,
                                             date_of_birth=dob, employee_address=employee_address, city_id=city_id,
                                            state_id=state_id, aadhar_number=aadhar_number, pan_number=pan_number, dep_id=dep_id,
                                            designation_id=designation_id, date_of_joining=date_of_joining, is_employee=True,)
            messages.success(request, 'Employee added sucesssully')
            # return render(request,'')
            # # return redirect()


        except Exception as e:
                return JsonResponse(  {
                    'error_msg': str(e), 
                    'status_code': 400
                })
    user = User.objects.filter(username=request.session.get('username'))
    emp_id = Employee.objects.filter(user=user.first()).first()
    cities =  City.objects.all()
    states = State.objects.all()
    deps = Department.objects.all()
    designation = Designation.objects.all()
            # print(cities)
    context = {
        'cities': cities,
        'states': states,
        'deps': deps,
        'designation': designation,
        'is_hr': emp_id.is_hr if emp_id else False  
    }

    return render(request,'add_employee.html', context)

def my_profile(request):
    if request.session.get('username'):
        user = User.objects.filter(username=request.session.get('username'))
        emp_id = Employee.objects.filter(user=user[0])
        print(emp_id[0].is_hr)
        context = {
            'username': request.session.get('username'),
            'emp': emp_id[0],
            'is_hr': emp_id[0].is_hr 
            
        }
    else:
        context = {}
        
    return render(request,'my_profile.html',context)

def view_all_employee(request):
    print(request.method)
    if request.method == 'POST':
        dep_name = request.POST.get('dep_filter')
        if dep_name == 'all':
            employess = Employee.objects.all()
        else:
            department = Department.objects.get(department_name=dep_name)
            employess = Employee.objects.filter(dep_id=department)
        context = {
            'employees': employess,
            'departments' : Department.objects.all()
        }
        return render(request,'view_all_employee.html', context)
    
    user = User.objects.filter(username=request.session.get('username'))
    emp_id = Employee.objects.filter(user=user[0]).first()

    all_deps = Department.objects.all()
    context = {
        'departments': all_deps,
        'employees': Employee.objects.all(),
        'is_hr': emp_id.is_hr
     }
    return render(request,'view_all_employee.html',context)

def index(request):
    if request.session.get('username'):
        user = User.objects.filter(username=request.session.get('username'))
        emp_id = Employee.objects.filter(user=user.first()).first()
        context = {
            'username': request.session.get('username'),
            'emp': emp_id,
            'is_hr': emp_id.is_hr
        }
        print(context)
    else:
        context = {}
    return render(request,'index.html', context)

    # Remove the 'username' from the session
    if 'username' in request.session:
        del request.session['username']
    
    logout(request)
    
    return redirect('login')

def add_department(request):
    user = User.objects.filter(username=request.session.get('username'))
    emp_id = Employee.objects.filter(user=user[0]).first()
    if request.method == 'POST':
        dep_name = request.POST.get('dep_name')
        dep = Department.objects.filter(department_name=dep_name)
        if dep:
            messages.success(request, 'Department Already Exist!')
            
        else:
            Department.objects.create(department_name=dep_name)
            # messages.success(request, 'Department added successfully!')
            return redirect('view_department')
    return render(request, 'add_department.html', {'is_hr': emp_id.is_hr})

def view_department(request):
    user = User.objects.filter(username=request.session.get('username'))
    emp_id = Employee.objects.filter(user=user[0]).first()
    context = {
        'deps': Department.objects.all(),
        'is_hr': emp_id.is_hr
    }
    return render(request, 'view_department.html', context)

@login_required
@csrf_protect
def fill_attendance(request):
    # Get the user object
    user = request.user

    # Initialize context with username
    context = {'username': user.username}

    # Get the employee object
    emp = Employee.objects.filter(user=user).first()
    context['is_hr'] = emp.is_hr

    if emp:
        # Check if attendance exists for today
        att_obj = Attendance.objects.filter(att_date=datetime.date.today(), emp_id=emp).first()

        if att_obj:
            context['in_time'] = att_obj.in_time
            context['out_time'] = att_obj.out_time

        if request.method == 'POST':
            if 'check_in' in request.POST:
                # Check if user has already checked in for the day
                if att_obj:
                    context['message'] = 'You have already checked in today.'
                else:
                    att_date = datetime.date.today()
                    in_time = time.strftime("%H:%M:%S", time.localtime())
                    att_obj = Attendance.objects.create(emp_id=emp, att_date=att_date, in_time=in_time)

hr/templates/about_us.html
{% extends 'index.html' %} {% block mycontent %}

<style>
  h3 {
    font-family: 'Times New Roman', Times, serif;
    text-align: center;
    font-weight: bold;
  }

  h2{
    font-family: 'Times New Roman', Times, serif;
    border-bottom: 2px solid green;
  }
  p {
    font-family: 'Times New Roman', Times, serif;
    font-weight: bold;
    text-align: justify;
  }
</style>

<div class="container">
  <h2 class="text-secondry p-2 text-left fs-1">
    About Us
  </h2>

  <div class="row text-center">
    <div class="col-sm-12 p-2">
      <div class="mb-3 About_us">
        <h3 class="About_us">
          About Us
        </h3>
        <p>
          Welcome to Olive Pvt Ltd, your trusted partner in managing company data. We specialize in providing
          innovative data management solutions that empower businesses to harness the full potential of their
          information assets. With a relentless commitment to excellence and a deep understanding of data's
          transformative power, Olive Pvt Ltd stands as a beacon of reliability in the ever-evolving landscape of
          data-driven decision-making.
        </p>
      </div>

      <div class="mission">
        <h3>Our Mission</h3>
        <p>
          At Olive Pvt Ltd, our mission is clear: to revolutionize the way companies perceive, handle, and utilize
          their data. We strive to streamline data processes, enhance data accuracy, and unlock valuable insights that
          drive growth, efficiency, and success. We are dedicated to fostering a data-conscious culture that
          transforms challenges into opportunities and complexity into clarity.
        </p>
      </div>

      <div class="text-left">
        <h3>Why Choose Olive Pvt Ltd?</h3>
        <p>
          Expertise: With a team of seasoned data professionals, we bring a wealth of expertise and knowledge to every
          project. We understand that every business is unique, and we tailor our solutions to meet your specific needs.
        </p>

        <p>
          Innovation: In a rapidly evolving digital landscape, innovation is key. We stay ahead of the curve by
          embracing the latest technologies and trends, ensuring that our clients always benefit from cutting-edge
          solutions.
        </p>

        <p>
          Reliability: Trust is the foundation of our client relationships. We prioritize data security, privacy, and
          integrity, ensuring that your information is always in safe hands.

          Results-Driven: We are not just about processes; we are about results. Our solutions are designed to deliver
          tangible outcomes, from increased operational efficiency to better-informed decision-making.
        </p>

      </div>
      <div class="text-left">
        <h3>Join Us on the Journey</h3>
        <p>
          Whether you're a start-up looking to establish a solid data foundation or a seasoned enterprise aiming to
          optimize your data strategies, Olive Pvt Ltd is here to accompany you every step of the way. Embrace the
          future of data management with us, and let's embark on a journey that transforms your data into a strategic
          asset. Contact us today to explore the possibilities.

          <p class="fs-10">
            Olive Pvt Ltd - Nurturing Insights, Empowering Growth.
          </p>
        </p>
      </div>
    </div>
  </div>
</div>

{% endblock%}

hr/templates/add_department.html
{% extends "index.html" %}

{% block mycontent %}


            <div class="container mt-5">
                <div class="row justify-content-center">
                  <div class="col-md-8">
                    <div class="card">
                      <div class="card-header">
                        <h1 class="card-title">Add Department</h1>
                      </div>
                      <div class="card-body">
                        <form class="custom-form" method="post">
                          {% csrf_token %}
                          <div class="mb-3">
                            <label for="dep_name"><b>Department Name</b></label>
                            <input type="text" id="dep_name" name="dep_name" class="form-control" required />
                          </div>
                          
                          <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">Submit</button>
                          </div>
                        </form>
                        {% if messages %}
                        <div class="messages mt-3">
                            {% for message in messages %}
                            <div class="alert alert-danger" role="alert">
                                {{ message }}
                            </div>
                            {% endfor %}
                        </div>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>

      
{% endblock %}

hr/templates/attendence_request.html
{% extends 'index.html' %}

{% block mycontent %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            <h1 class="card-title">Attendance Request</h1>
          </div>
          <div class="card-body">
            <form class="custom-form" method="post">
              {% csrf_token %}
              <div class="mb-3">
                <label for="request_type" class="form-label">Request Type</label>
                <select class="form-select" id="request_type" name="request_type">
                  <option value="new">New Request</option>
                  <option value="change">Change Request</option>
                </select>
              </div>
              <div class="mb-3">
                <label for="att_date" class="form-label">Date</label>
                <input type="date" class="form-control" id="att_date" name="att_date" />
              </div>
              <div class="row">
                <div class="col-md-6 mb-3">
                  <label for="intime" class="form-label">In Time</label>
                  <input type="time" class="form-control" id="intime" name="intime" />
                </div>
                <div class="col-md-6 mb-3">
                  <label for="outtime" class="form-label">Out Time</label>
                  <input type="time" class="form-control" id="outtime" name="outtime" />
                </div>
              </div>
              <div class="mb-3">
                <label for="note" class="form-label">Appropriate Reason With Refrence</label>
                <textarea class="form-control" id="note" name="note" rows="3"></textarea>
              </div>
              <div class="d-grid gap-2">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
              {% if messages %}
                  <div class="messages">
                  {% for message in messages %}
                  <div class="alert alert-sucess my-3" role="alert">
                        {{ message }}
                    </div>
                   {% endfor %}
                  </div>
              {% endif %}
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

hr/templates/change_password.html
{% extends "index.html" %}

{% block mycontent %}

{% comment %} <script type="text/javascript">
    function checkpassword()
    {
        if(document.changePassword.newpassword.value!=document.changePassword.confirmpassword.value)
        {
            alert('New password And Confirm Password filed does not match');
            document.changePassword.confirmpassword.focus();
            return false;
        }
        return true;
    } {% endcomment %}

</script>
<div style="width:100%" class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            <h1 class="card-title">Change Password</h1>
          </div>
          <div class="card-body">
            <form class="custom-form" method="post">
              {% csrf_token %}
              <div style="width:100%" class="mb-3">
                <label for="currentpassword" class="form-label">Current Password</label>
                <input type="password" class="form-control" id="currentpassword" name="currentpassword" / required>
              </div>
              <div class="mb-3">
                <label for="newpassword" class="form-label">New Password</label>
                <input type="password" class="form-control" id="newpassword" name="newpassword" required />
              </div>
              <div class="mb-3">
                <label for="confirmpassword" class="form-label">Confirm New Password</label>
                <input type="password" class="form-control" id="confirmpassword" name="confirmpassword" required/>
              </div>
              <div class="d-grid gap-2">
                <button type="submit" class="btn btn-primary">Change Password</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>


{% if error == "no" %}
<script>
    alert('Password Updated successfully');
    {% comment %} window.location = ('{% url '' %}'); {% endcomment %}
</script>
{% endif %}
{% if error == "yes" %}
<script>
    alert('Something Went Wrong, your password and confirm password are not same');  

</script>
{% endif %}

{% if error == "not" %}
<script>
    alert('Your current password is wrong, try Again...');  

</script>
{% endif %}

{% endblock %}

hr/templates/deactivate_employee.html
{% extends 'index.html' %}

{% block mycontent %}

<div class="container mt-5">
    <h2>Confirm Deletion</h2>
    <p>Are you sure you want to delete the employee '{{ employee.user.get_full_name }}'?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, Delete</button>
        <a href="{% url 'view_all_employee' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>

{% endblock %}

hr/templates/fill_attendance.html
{% extends "index.html" %}

{% block mycontent %}
<div style="position: absolute; top: 60%; left: 60%; transform: translate(-60%, -60%); text-align: center;">
    <h1>Welcome {{ username }}</h1>
    <br/>
    {% if in_time %}
    <p>You have Entered office at {{ in_time }}</p>
    {% endif %}
    {% if out_time %}
    <p>You have Checked Out at {{ out_time }}</p>
    {% endif %}
    {% if message %}
    <p>{{ message }}</p>
    {% endif %}
    {% if not in_time and not out_time %}
    <form method='post'>
        {% csrf_token %}
        <button type="submit" name='check_in' style="padding: 20px 40px; font-size: 24px; background-color: #007bff; color: #fff; border: none; border-radius: 5px; cursor: pointer;">
            Check In
        </button>
    </form>
    {% endif %}
    {% if in_time and not out_time %}
    <form method='post'>
        {% csrf_token %}
        <button type="submit" name='check_out' style="padding: 20px 40px; font-size: 24px; background-color: #0F7bff; color: #fff; border: none; border-radius: 5px; cursor: pointer;">
            Check Out
        </button>
    </form>
    {% endif %}
</div>
{% endblock %}

hr/templates/show_attendence_graph.html
{% extends 'index.html' %}

{% block mycontent %}
<div class="container mt-5">
  <h1>Show Your Attendence for the Selected Dates</h1>
<form method="get" action="{% url 'show_attendence_graph' %}" class="row g-3 align-items-center">
  <div class="col-auto">
    <label for="start_date">From Date:</label>
</div>
<div class="col-auto">
    <input type="date" id="start_date" name="start_date" class="form-control" value="{{ start_date }}" required>
</div>
<div class="col-auto">
    <label for="end_date">To Date:</label>
</div>
<div class="col-auto">
    <input type="date" id="end_date" name="end_date" class="form-control" value="{{ end_date }}" required>
</div>
<div class="col-auto">
  <button type="submit" class="btn btn-primary">Apply Filter</button>
</div>
</form>
  <div style="width: 80%; margin: 0 auto; width: 1000px; height: 1000px;">{{ graph|safe }}</div>
</div>
{% endblock %}

hr/templates/view_attendence_request.html
{% extends 'index.html' %}

{% block mycontent %}
  <div class="container mt-5">
    <h1>Attendance Requests</h1>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Employee</th>
          <th>Date</th>
          <th>In Time</th>
          <th>Out Time</th>
          <th>Request Type</th>
          <th>Status</th>
          <th>Reason</th>
          <th>Approve/Reject</th>
        </tr>
      </thead>
      <tbody>
        {% if attendance_records %}
            {% for attendance in attendance_records %}
                <tr>
                    <td>{{ attendance.emp_id }}</td>
                    <td>{{ attendance.att_date }}</td>
                    <td>{{ attendance.in_time }}</td>
                    <td>{{ attendance.out_time }}</td>
                    <td>{{ attendance.get_request_type_display }}</td>
                    <td>{{ attendance.get_status_display }}</td>
                    <td>{{ attendance.note }}</td>
                    <td>
                        <a href="{% url 'accept_reject_attendance' attendance.id 'approve' %}">
                            <button type="button" class="btn btn-success">Accept</button>
                        </a>
                        <a href="{% url 'accept_reject_attendance' attendance.id 'reject' %}">
                            <button type="button" class="btn btn-danger">Reject</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="8" style="text-align: center;">No Records Found</td>
            </tr>
        {% endif %}
    </tbody>
    </table>
  </div>
{% endblock %}